# Hello, [NumPy](https://numpy.org/doc/stable/reference/)!

<img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.vPezx00A1u0WAfS8e8wBXQHaHa%26pid%3DApi&f=1" alt="drawing" width="200"/>



What is NumPy?

- the core library for **scientific computing** in Python;
- almost all of the libraries in the [PyData](https://pydata.org/) ecosystem (`pandas`, `scipy`, `scikit-learn`, etc.) and many deep learning frameworks such as [Tensorflow](https://www.tensorflow.org/) and [PyTorch](https://pytorch.org/) **rely on NumPy as one of their main building blocks**;
- the main advantage of NumPy is that **it's incredibly fast**, as it has bindings to C libraries.

NumPy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects such as:
- arrays;
- vectors;
- matrices;
- number generation.

# NumPy Arrays

NumPy arrays are the main way we will use NumPy throughout the course. They come in two flavors: vectors and matrices.
- vectors are 1-dimensional (1D) arrays;
- matrices are 2-dimensional (2D) arrays (but you should note a matrix can still have only one row or one column);
- we'll call any structure that has 3 or more dimensions just an array or tensor;
- NumPy arrays are **homogeneours**. They can't hold multiple types!

## Why not just a list?

Some reasons are:
- Memory Efficiency of Numpy Array vs list;
- Easily expands to N-dimensional arrays;
- Speed of calculations of numpy array;
- **Broadcasting** operations and functions with numpy;
- All machine learning libraries we use are built with Numpy;
- For a discussion on why you would want to use NumPy arrays instead of Python lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

## Some terminology

- **Axis**: The number of the dimension (an non-negative integer).
- **Shape**: The number of elements in a dimension (a tuple).

1D array:

![1d_array](https://raw.githubusercontent.com/SimeonHristov99/ML_22-23/main/assets/1d.png)

2D array:

![2d_array](https://raw.githubusercontent.com/SimeonHristov99/ML_22-23/main/assets/2d.png)

3D array:

![3D array](https://raw.githubusercontent.com/SimeonHristov99/ML_22-23/main/assets/3d.png)

In [3]:
# Import numpy
import numpy as np

# Notice the alias.

In [4]:
# Check the version of numpy
np.__version__

# Note that we have two consecutive underlines ('_')
# before the 'v' and after the 'n'.

'1.24.2'

# Creating NumPy Arrays

## From Python Lists

We can create an array by directly converting a list or list of lists.

In [5]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [6]:
np.array(my_list)

array([1, 2, 3])

In [7]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
# Of course we don't need to have a predefined variable.
np.array([1,2,3])

array([1, 2, 3])

## Using built-in methods

There are lots of built-in ways to generate arrays.

## arange

The analog to the Python `range` function. [[reference](https://numpy.org/doc/stable/reference/generated/numpy.arange.html?highlight=arange#numpy.arange)]

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

## zeros and ones

Generate arrays of zeros or ones. [[reference](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html?highlight=zeros#numpy.zeros)]

Note that the resulting arrays hold **floating point** numbers.

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones(3)

array([1., 1., 1.])

In [16]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## linspace 

Return evenly spaced numbers over a specified interval. [[reference](https://www.numpy.org/devdocs/reference/generated/numpy.linspace.html)]

In [17]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [18]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

> **Note**: `.linspace()` *includes* the stop value.

To obtain an array of common fractions, increase the number of items:

In [19]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

## eye

Creates an identity matrix [[reference](https://numpy.org/doc/stable/reference/generated/numpy.eye.html?highlight=eye#numpy.eye)]. The resulting array holds floating point numbers.

In [20]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays.

### rand
Creates an array of the given shape and populates it with random samples from a uniform distribution over ``[0, 1)`` [[reference](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html?highlight=rand#numpy.random.rand)].

Read more about the uniform distribution [here](https://www.wallstreetmojo.com/uniform-distribution/).

In [21]:
np.random.rand(2)

array([0.48752171, 0.77321035])

In [22]:
np.random.rand(5,5)

array([[0.1042745 , 0.72094753, 0.58054663, 0.38005437, 0.13557961],
       [0.26309775, 0.89925489, 0.81092012, 0.10267348, 0.86565351],
       [0.94186463, 0.76073878, 0.14698801, 0.86335036, 0.21994433],
       [0.13392627, 0.16436193, 0.10777611, 0.35737696, 0.80237186],
       [0.00594299, 0.20201119, 0.49688822, 0.63168501, 0.70971642]])

In [23]:
samples = np.random.rand(10000)
print(f'Expected mean if true uniform distribution: {1 / 2}. Got: {samples.mean()}')
print(f'Expected standard deviation if true uniform distribution: {np.sqrt(1 / 12)}. Got: {samples.std()}')

Expected mean if true uniform distribution: 0.5. Got: 0.5042603381728517
Expected standard deviation if true uniform distribution: 0.28867513459481287. Got: 0.28973632825508244


### randn

Returns a sample (or samples) from the "standard normal" distribution [σ = 1]. Unlike **rand** which is uniform, values closer to zero are more likely to appear [[reference](https://numpy.org/doc/stable/reference/random/generated/numpy.random.randn.html?highlight=randn#numpy.random.randn)].

Read more about the standard normal distribution [here](https://online.stat.psu.edu/stat500/lesson/3/3.3/3.3.2).

In [24]:
np.random.randn(2)

array([-1.53791519,  0.25469736])

In [25]:
np.random.randn(5,5)

array([[-0.65190794, -0.07048945, -1.62079734, -0.40556925, -0.12858131],
       [-1.21239873,  2.29415778,  0.39212379,  0.14543334, -0.71388686],
       [-1.27715822, -0.28316553,  0.37282847, -0.64677913, -2.13354299],
       [-0.23872004, -0.42982364, -1.0286424 , -0.98539987,  0.07564372],
       [ 1.43375693, -1.43333331,  1.5485272 , -1.86579571,  0.37795988]])

In [26]:
print(np.random.randn(10000).mean())
print(np.random.randn(10000).std())

-0.018585562680740218
1.0087479962355526


### randint

Returns random integers from `low` (inclusive) to `high` (exclusive) drawn from the discrete uniform distribution.  [[reference](https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html?highlight=randint#numpy.random.randint)]

In [27]:
np.random.randint(1,100)

12

In [28]:
np.random.randint(1,100,10)

array([99, 77, 32, 59, 35, 38, 64, 80, 29, 84])

In [29]:
np.random.randint(1,100,(10, 10))

array([[35, 50, 48, 11, 25, 54, 42, 62, 69, 91],
       [16, 66, 74,  6, 54, 81, 79, 18,  6, 31],
       [65, 43, 27, 74, 50, 41, 77, 17, 68, 36],
       [84,  5, 63, 28, 74, 76, 72, 77,  9,  8],
       [60, 81,  4, 65, 46,  5, 45, 91, 18, 47],
       [12, 72,  5, 74, 11, 34, 10,  7, 49, 47],
       [11, 71, 53, 90, 68, 61, 28, 96, 43, 81],
       [69, 82, 87, 81, 80, 66, 40, 90, 49, 18],
       [13, 85, 92, 43, 24,  1, 16, 34, 99, 46],
       [38, 26, 23, 14, 80, 27, 73, 44, 93, 59]])

In [30]:
np.random.randint(1, 100, 1000).mean()

49.403

### seed

Can be used to set the random state, so that the same "random" results can be reproduced.

In [31]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [32]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

# Useful Attributes and Methods

In [33]:
arr = np.arange(25)
rand_arr = np.random.randint(0,50,10)

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [35]:
rand_arr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

## Reshape

Returns an array containing the same data with a new shape.

In [36]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

> **Note**: The product of the elements in the new shape **MUST** equal the total number of elements! 

In [37]:
# Get the total number of elements
arr.size

25

In [38]:
# arr.reshape(4,5)

## max, min, argmax, argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [39]:
rand_arr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [40]:
rand_arr.max()

39

In [41]:
rand_arr.argmax()

7

In [42]:
rand_arr.min()

2

In [43]:
rand_arr.argmin()

9

## Shape


In [44]:
# Vector
arr.shape

(25,)

In [45]:
# Matrix
arr.reshape(5,5).shape

(5, 5)

In [46]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [47]:
# Notice the two sets of brackets in the output

arr.reshape(1,25).shape

(1, 25)

In [48]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [49]:
arr.reshape(25,1).shape

(25, 1)

### dtype

Grab the data type of the object in the array.

In [50]:
arr.dtype

dtype('int32')

In [51]:
arr2 = np.array([1.2, 3.4, 5.6])
arr2.dtype

dtype('float64')

# Indexing and Selection

How to select elements or groups of elements from an array?

In [52]:
#Creating a sample array
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Bracket Indexing and Selection

The simplest way to pick one or some elements of an array looks very similar to Python lists.

In [53]:
#Get a value at an index
arr[8]

8

In [54]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [55]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

### **Broadcasting**

NumPy arrays differ from normal Python lists because of their ability to **broadcast**.

- in general, allows for working with arrays of different shapes
- with lists, you can only reassign parts of a list with new parts of the same size and shape. That is, if you wanted to replace the first 5 elements in a list with a new value, you would have to pass in a new 5 element list. With NumPy arrays, you can broadcast a single value across a larger set of values.

In [56]:
x = np.array([[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]])
a = np.array([1, 0, 1])

print(x)
print(a)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[1 0 1]


In [57]:
x.shape

(4, 3)

In [58]:
a.shape

(3,)

In [59]:
# Technically, we should have the same shape on both arrays, but numpy can automatically create it for us.
x + a

array([[2, 2, 4],
       [5, 5, 7],
       [2, 2, 4],
       [5, 5, 7]])

In [60]:
print(a + np.array([3,3,3]))
# broadcasting makes it easier to write
# code like this
print(a + 3)

[4 3 4]
[4 3 4]


In [61]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

> **Note**: Changes in sliced arrays get propagated to the original array.

In [62]:
# Reset
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
#Important notes on slices
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

`slice_of_arr` is **NOT** a copy of `arr`. It is a direct reference to its elements.

In [64]:
#Change Slice
slice_of_arr[:] = 99

# Slice has changed
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [65]:
# But so has the original array
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [66]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [67]:
arr_copy[:] = 777

print(arr_copy)
print(arr)

[777 777 777 777 777 777 777 777 777 777 777]
[99 99 99 99 99 99  6  7  8  9 10]


## Indexing a 2D array (matrices)

The general format is `arr_2d[row][col]` or `arr_2d[row, col]`. The more common approach is to use the comma notation.

In [68]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [69]:
# Indexing row
arr_2d[1]

array([20, 25, 30])

In [70]:
arr_2d[2]

array([35, 40, 45])

In [71]:
# Getting individual element value
arr_2d[1][0]

20

In [72]:
# Using the comma notation
arr_2d[1, 0]

20

In [73]:
# 2D array slicing

# Get all the elements from the bottom row
arr_2d[2,:]

array([35, 40, 45])

In [74]:
# Grabbing the top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

## Indexing is Often Confusing

Indexing a 2D matrix can be a bit confusing at first, especially when you start to add in step size. Try google image searching *NumPy indexing* to find useful images, like this one:

![pic](https://scipy-lectures.org/_images/numpy_indexing.png)

## Conditional Selection

This is **an important concept** that will directly translate to `pandas` later on!

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [75]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [77]:
bool_arr = arr > 4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [78]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [79]:
# Most commonly, the boolean array (also called mask)
# is not stored in a variable.
arr[arr > 2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [80]:
x = 2
arr[arr > x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

# NumPy Operations

## Arithmetic

You can easily perform *array with array* arithmetic, or *scalar with array* arithmetic thanks to broadcasting. Let's see some examples:

In [81]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [83]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [84]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [85]:
# This will raise a Warning on division by zero, but not an error!
# It just fills the spot with nan (Not A Number)
arr/arr

C:\Users\c86608b\AppData\Local\Temp\1\ipykernel_22128\2764682297.py:3: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [86]:
# Also a warning (but not an error) relating to infinity
1 / arr

C:\Users\c86608b\AppData\Local\Temp\1\ipykernel_22128\3242981687.py:2: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [87]:
# See the power of broadcasting
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

## Universal Array Functions

NumPy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), or <em>ufuncs</em>, which are essentially just mathematical operations that can be applied across the array.<br>Let's show some common ones:

In [88]:
# Taking Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [89]:
# Calculating exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [90]:
# Trigonometric Functions like sine
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [91]:
# Taking the Natural Logarithm
np.log(arr)

C:\Users\c86608b\AppData\Local\Temp\1\ipykernel_22128\2367246271.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

## Summary Statistics on Arrays

NumPy also offers common summary statistics like <em>sum</em>, <em>mean</em> and <em>max</em>. You would call these as methods on an array.

In [92]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
arr.sum()

45

In [94]:
arr.mean()

4.5

In [95]:
arr.max()

9

<strong>Other summary statistics include:</strong>
<pre>
arr.min() returns 0                   minimum
arr.var() returns 8.25                variance
arr.std() returns 2.8722813232690143  standard deviation
</pre>

## Axis Logic
When working with 2-dimensional arrays (matrices) we have to consider rows and columns. This becomes very important when we get to the section on `pandas`. In array terms, axis 0 (zero) is the vertical axis (rows), and axis 1 is the horizonal axis (columns). These values (0,1) correspond to the order in which <tt>arr.shape</tt> values are returned.

Let's see how this affects our summary statistic calculations from above.

In [96]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [97]:
arr_2d.sum(axis=0)

array([15, 18, 21, 24])

By passing in <tt>axis=0</tt>, we're returning an array of sums along the vertical axis, essentially <tt>[(1+5+9), (2+6+10), (3+7+11), (4+8+12)]</tt>

In [98]:
arr_2d.shape

(3, 4)

This tells us that <tt>arr_2d</tt> has 3 rows and 4 columns.

So what should <tt>arr_2d.sum(axis=1)</tt> return?

In [99]:
arr_2d.sum(axis=1)

array([10, 26, 42])

# Let's try it out

## Task 1

Create a numpy array of `101` evenly linearly spaced points between `0` and `10`. Assign this array to a variable called `arr`. Print `arr`.

In [107]:
# Your code here
arr = np.linspace(0, 10, 101)
print(f'Resulting array: {arr}')

Resulting array: [ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1.   1.1  1.2  1.3
  1.4  1.5  1.6  1.7  1.8  1.9  2.   2.1  2.2  2.3  2.4  2.5  2.6  2.7
  2.8  2.9  3.   3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8  3.9  4.   4.1
  4.2  4.3  4.4  4.5  4.6  4.7  4.8  4.9  5.   5.1  5.2  5.3  5.4  5.5
  5.6  5.7  5.8  5.9  6.   6.1  6.2  6.3  6.4  6.5  6.6  6.7  6.8  6.9
  7.   7.1  7.2  7.3  7.4  7.5  7.6  7.7  7.8  7.9  8.   8.1  8.2  8.3
  8.4  8.5  8.6  8.7  8.8  8.9  9.   9.1  9.2  9.3  9.4  9.5  9.6  9.7
  9.8  9.9 10. ]


In [101]:
# Expected output

Resulting array: [ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1.   1.1  1.2  1.3
  1.4  1.5  1.6  1.7  1.8  1.9  2.   2.1  2.2  2.3  2.4  2.5  2.6  2.7
  2.8  2.9  3.   3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8  3.9  4.   4.1
  4.2  4.3  4.4  4.5  4.6  4.7  4.8  4.9  5.   5.1  5.2  5.3  5.4  5.5
  5.6  5.7  5.8  5.9  6.   6.1  6.2  6.3  6.4  6.5  6.6  6.7  6.8  6.9
  7.   7.1  7.2  7.3  7.4  7.5  7.6  7.7  7.8  7.9  8.   8.1  8.2  8.3
  8.4  8.5  8.6  8.7  8.8  8.9  9.   9.1  9.2  9.3  9.4  9.5  9.6  9.7
  9.8  9.9 10. ]


## Task 2

Check how many rolls were greater than `2`. For example if `dice_rolls=[1,2,3]` then the answer is `1`.

In [102]:
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])

# Your code here
print(f'{dice_rolls[dice_rolls > 2].size=}')
print(f'{dice_rolls.size=}')

dice_rolls[dice_rolls > 2].size=19
dice_rolls.size=29


In [103]:
# Expected output

19

## Task 3

A bank account has had withdrawals and deposits tracked in a numpy array called `account_transactions`. Based on this list of account transactions, what is the total remaining in the account?

In [104]:
# Solution
account_transactions = np.array([100,-200,300,-400,100,100,-230,450,500,2000])

# Your code here
account_transactions.sum()

2720

In [105]:
# Expected output

2720