#### 1. Import NumPy

Make sure to follow the conventions!

In [3]:
import numpy as np

#### 2. Create an array of 10 zeros 

In [40]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
# Expected output

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3. Create an array of 10 ones

In [41]:
np.ones(1)

array([1.])

In [ ]:
# Expected output

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 4. Create an array of 10 fives

In [10]:
# np.array([5.] * 10)
np.ones(1) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [ ]:
# Expected output

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### 5. Create a vector, named `arr`, of 10 zeros the fifth value of which is 1.

In [43]:
arr = np.zeros(10)
arr[5] = 1

arr

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [ ]:
# Expected output

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 6. Create an array of the integers from 10 to 50

In [45]:
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [16]:
# Expected output


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### 7. Reverse an array in **TWO** ways: using 'the Python way' and using a NumPy function

In [37]:
print(f"Using the Python way: {np.array([1, 2, 3])[::-1]}")
print(f"Using the NumPy function: {np.flip(np.array([1, 2, 3]))}")

Using the Python way: [3 2 1]
Using the NumPy function: [3 2 1]


In [ ]:
# Expected output

Using the Python way: [3 2 1]
Using a NumPy function: [3 2 1]


#### 8. Create a 5x5 array with 1 on the border and 0 inside

In [50]:
arr = np.ones((5, 5))
arr[1:-1, 1:-1] = 0
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# Expected output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 9. Add a border filled with 0's on the two sides of an array.

> Hint: [np.pad](https://numpy.org/doc/stable/reference/generated/numpy.pad.html)

In [54]:
arr = np.array([1, 2, 3])
np.pad(arr, 1)


array([0, 1, 2, 3, 0])

In [ ]:
# Expected output

array([0, 1, 2, 3, 0])

#### 10. Create an array of all the even integers from 10 to 50

In [56]:
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [ ]:
# Expected output

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### 11. Create a 3x3 matrix with values ranging from 0 to 8

In [61]:
np.arange(0, 9).reshape((3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# Expected output

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 12. Create a 3x3 identity matrix

In [62]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Expected output

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 13. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

> Hint: [np.diag](https://numpy.org/doc/stable/reference/generated/numpy.diag.html)

In [67]:
np.diag(np.arange(1, 5), -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [ ]:
# Expected output

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 14. Use NumPy to generate a random number between 0 and 1

**Note**: Your result's value should be different from the one shown below.

In [76]:
np.random.rand(1)

array([0.32761119])

In [ ]:
# Expected output

array([0.65248055])

#### 15. Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

**Note**: Your result's values should be different from the ones shown below.

In [79]:
np.random.randn(25)

array([ 0.09274539,  0.50475968,  0.44803323, -0.36623838, -0.04334177,
        1.26415116, -0.50074405, -1.27576392, -0.4794695 ,  0.97095661,
        1.97320794, -0.67971797, -0.39712603, -0.90175578, -1.78315191,
        1.35848885, -0.71150977, -0.54158525,  0.90490253, -2.2691338 ,
        0.25332595, -1.48433177, -0.55966328, -0.6532323 , -0.65240707])

In [ ]:
# Expected output

array([ 1.80076712, -1.12375847, -0.98524305,  0.11673573,  1.96346762,
        1.81378592, -0.33790771,  0.85012656,  0.0100703 , -0.91005957,
        0.29064366,  0.69906357,  0.1774377 , -0.61958694, -0.45498611,
       -2.0804685 , -0.06778549,  1.06403819,  0.4311884 , -1.09853837,
        1.11980469, -0.48751963,  1.32517611, -0.61775122, -0.00622865])

#### 16. Create a 3x3x3 array with random values drawn from the uniform distribution

**Note**: Your result's values should be different from the ones shown below.


In [81]:
np.random.rand(27).reshape((3, 3, 3))

array([[[0.60001812, 0.85851888, 0.81511598],
        [0.62145189, 0.19774356, 0.12884685],
        [0.25024429, 0.92638304, 0.65681204]],

       [[0.6697461 , 0.69716723, 0.94712333],
        [0.49498455, 0.46757868, 0.85354001],
        [0.6034639 , 0.07904896, 0.11348394]],

       [[0.56717263, 0.21570533, 0.64278054],
        [0.31093055, 0.32385977, 0.70075784],
        [0.31627541, 0.77759983, 0.66078194]]])

In [ ]:
# Expected output

array([[[0.93641099, 0.2920839 , 0.02292815],
        [0.00336922, 0.86947306, 0.68416644],
        [0.8901026 , 0.3837379 , 0.28653589]],

       [[0.10726099, 0.43744832, 0.00470833],
        [0.29069139, 0.64529908, 0.85020447],
        [0.51284435, 0.41215324, 0.19622211]],

       [[0.43004522, 0.92649706, 0.09472069],
        [0.76510854, 0.49565729, 0.56232861],
        [0.07813665, 0.49086324, 0.45172232]]])

#### 17. Create a 10x10 array with random values drawn from the uniform distribution and find the minimum and maximum values.

**Note**: Your result's values should be different from the ones shown below.

In [84]:
arr = np.random.rand(100).reshape((10, 10))
print(f"The array: {arr}")
print(f"Its min value: {np.min(arr)}")
print(f"Its max value: {np.max(arr)}")



The array: [[8.46961016e-01 8.98784848e-01 4.46619747e-01 8.18223374e-01
  4.99474370e-01 9.75452638e-01 6.31719710e-02 3.27622405e-01
  7.09776195e-01 6.85507265e-01]
 [4.54605050e-01 1.98752791e-01 4.66160895e-01 4.97971195e-01
  3.45631498e-01 3.30753598e-01 1.17164430e-01 6.14492453e-01
  1.17589998e-01 2.28164426e-01]
 [8.93920386e-01 1.47940065e-01 7.49022863e-01 8.43662684e-01
  4.23219179e-01 8.16766510e-01 3.32951461e-01 1.66299300e-01
  3.61129474e-03 8.95060269e-01]
 [7.30681310e-01 3.28267768e-02 4.93767694e-01 1.57510422e-01
  4.53571388e-01 9.87867742e-01 3.01459412e-01 2.15846515e-04
  8.09771964e-02 8.30648881e-01]
 [5.12481896e-01 1.68779638e-01 9.61632926e-01 9.75498747e-03
  4.29510261e-01 1.23630370e-01 2.03942248e-01 3.06683593e-01
  8.71104306e-01 3.51652378e-03]
 [5.94227108e-01 2.93421861e-01 3.38701729e-01 9.25348735e-01
  2.25018785e-01 8.47657224e-01 1.52071720e-01 5.21277151e-01
  9.37375732e-01 8.56767523e-01]
 [3.34200230e-01 1.41613178e-01 7.33199780e-01 

In [ ]:
# Expected output

The array: [[0.19932859 0.92905065 0.55492647 0.09878608 0.0421074  0.74219358
  0.92844055 0.62528946 0.35357668 0.88013918]
 [0.36971412 0.74932736 0.02445995 0.72873717 0.48864481 0.14421664
  0.56846658 0.40363749 0.3233466  0.95147426]
 [0.98339368 0.39612436 0.03609193 0.10611245 0.1410213  0.21099682
  0.3285783  0.39140252 0.88863881 0.81498748]
 [0.25423077 0.0756975  0.77587885 0.29315387 0.56795003 0.90145549
  0.95278316 0.63800115 0.14696466 0.08528442]
 [0.08048731 0.55554534 0.21157669 0.37491896 0.95567126 0.72478012
  0.64849367 0.05571253 0.12339177 0.95575902]
 [0.90842177 0.74316806 0.61710506 0.05885491 0.88051201 0.86814746
  0.26131788 0.89392307 0.45475956 0.26810516]
 [0.79185601 0.19973093 0.10674687 0.9080987  0.50335231 0.17405093
  0.39030326 0.48112173 0.74450033 0.76288692]
 [0.68992283 0.52305591 0.94364282 0.623963   0.04065964 0.23544532
  0.38685327 0.9687442  0.529897   0.37273771]
 [0.88262217 0.90518014 0.24570464 0.49601259 0.23893452 0.53227759
 

#### 18. Create a random array with values drawn from the uniform distribution of size 30 and find the mean value

In [92]:
arr = np.random.rand(30)
print(f"The array: {arr}")
print(f"Its mean value: {np.mean(arr)}")

The array: [0.38840922 0.98279965 0.1519079  0.98775509 0.93357312 0.71026877
 0.85458447 0.4279127  0.04209431 0.68961087 0.78500802 0.49595383
 0.74733347 0.39240556 0.38822728 0.22702752 0.49612162 0.74047934
 0.27308028 0.47560347 0.64618624 0.47249899 0.43922528 0.21886667
 0.77597333 0.68636713 0.75760648 0.07516378 0.75436132 0.54632541]
Its mean value: 0.5520910380173591


In [ ]:
# Expected output

The array: [0.65580703 0.66012918 0.44607318 0.08230611 0.03965247 0.98197551
 0.07286258 0.08288793 0.5283879  0.26948948 0.29579988 0.44204416
 0.42570657 0.74707057 0.96866384 0.96437312 0.38116077 0.74621085
 0.26497925 0.33115365 0.963408   0.05087827 0.36557266 0.66121816
 0.24851936 0.25971588 0.40104167 0.90926914 0.80488701 0.31365462]
Its mean: 0.4788299599451823


#### 19. Create the following matrix:

In [93]:
np.arange(1, 101).reshape((10, 10)) / 100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [ ]:
# Expected output

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### 20. Create an array of 20 linearly spaced points between 0 and 1:

In [94]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
# Expected output

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a starting matrix (be sure to run the cell below!), and be asked to replicate the resulting matrix outputs.

In all of the solutions until the last task before the section `NumPy Operations` you should be using `mat`.

In [96]:
# RUN THIS CELL - THIS IS OUR STARTING MATRIX
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### 21. Write code that reproduces the output shown below.

In [97]:
mat[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
# Expected output

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

#### 22. Write code that reproduces the output shown below.

In [100]:
mat[3, 4]

20

In [ ]:
# Expected output

20

#### 23. Write code that reproduces the output shown below.

In [106]:
mat[:3, 1:2]

array([[ 2],
       [ 7],
       [12]])

In [ ]:
# Expected output

array([[ 2],
       [ 7],
       [12]])

#### 24. Write code that reproduces the output shown below.

In [112]:
mat[4, :]

array([21, 22, 23, 24, 25])

In [ ]:
# Expected output

array([21, 22, 23, 24, 25])

#### 25. Write code that reproduces the output shown below.

In [115]:
mat[3:5, :]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# Expected output

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### 26. Find the indices of the non-zero elements in the provided array.

In [132]:
arr = np.array([1,2,0,0,4,0])
np.where(arr != 0)
# Your code here

(array([0, 1, 4]),)

In [ ]:
# Expected output

array([0, 1, 4])

## NumPy Operations

#### 27. Get the sum of all the values in mat

In [133]:
np.sum(mat)

325

In [ ]:
# Expected output

325

#### 28. Get the standard deviation of the values in mat

In [134]:
np.std(mat)

7.211102550927978

In [ ]:
# Expected output

7.211102550927978

#### 29. Get the sum of all the columns in mat

In [141]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [ ]:
# Expected output

array([55, 60, 65, 70, 75])

#### 30. Create and multiply a 5x3 matrix by a 3x2 matrix (matrix product). The matrices can hold random values or you can create them manually.

**Note**: In this example output the matrices held random values, so your result's values should be different from the ones shown below.

In [150]:
mat1 = np.random.rand(15).reshape((5, 3))
mat2 = np.random.rand(6).reshape((3, 2))

np.matmul(mat1, mat2)

array([[0.61686258, 0.69570062],
       [0.8381232 , 1.01982831],
       [0.72519803, 1.23910951],
       [0.42179752, 0.59368917],
       [1.05965181, 1.18471538]])

In [ ]:
# Expected output

array([[0.92284566, 0.4834381 ],
       [1.36591969, 0.86692985],
       [0.92732258, 0.57791729],
       [1.20870496, 0.66362074],
       [1.48551291, 0.86352205]])

#### 31. Create a 1D array of random integers between 0 and 9. Negate all elements which are between 3 and 8.

In [199]:
arr = np.random.randint(low=0, high=10, size=10)
mask = (arr >= 3) & (arr <= 8)
arr[mask] *= -1

arr

array([ 0, -6, -3,  0, -6, -3, -7, -5, -7, -5])

In [ ]:
# Expected output

array([ 4,  2,  5, -7, -2,  0, -3, -6, -8,  4])

#### 32. Create a random array of size 10 and sort it

In [204]:
arr = np.random.randint(low=0, high=10, size=10)
arr.sort()

arr

array([0, 2, 4, 4, 4, 6, 6, 8, 8, 8])

In [ ]:
# Expected output

array([0.21557229, 0.29775351, 0.31513898, 0.48094387, 0.56395818,
       0.61094507, 0.65782361, 0.73666887, 0.74573749, 0.97557176])

#### 33. Create random vector of values drawn from the uniform distribution of size 10 and replace the maximum value by 0

In [211]:
arr = np.random.randint(low=0, high=10, size=10)

print(f"The array: {arr}")

arr[arr == np.max(arr)] = 0
print(f"Result: {arr}")


The array: [6 9 9 7 2 5 5 7 4 0]
Result: [6 0 0 7 2 5 5 7 4 0]


In [ ]:
# Expected output

The array: [0.79753115 0.51085823 0.86710259 0.25025854 0.39803838 0.65002613
 0.89686752 0.1562022  0.76741728 0.62775096]
Result: [0.79753115 0.51085823 0.86710259 0.25025854 0.39803838 0.65002613
 0.         0.1562022  0.76741728 0.62775096]


#### 34. What function can we use to ensure that we always get the same random numbers?

seed