#### 1. Import NumPy

Make sure to follow the conventions!

In [2]:
import numpy as np

#### 2. Create an array of 10 zeros 

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
# Expected output

#### 3. Create an array of 10 ones

In [5]:
np.ones(1)

array([1.])

In [6]:
# Expected output

#### 4. Create an array of 10 fives

In [7]:
# np.array([5.] * 10)
np.ones(1) * 5

array([5.])

In [8]:
# Expected output

#### 5. Create a vector, named `arr`, of 10 zeros the fifth value of which is 1.

In [9]:
arr = np.zeros(10)
arr[5] = 1

arr

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [10]:
# Expected output

#### 6. Create an array of the integers from 10 to 50

In [11]:
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [12]:
# Expected output


#### 7. Reverse an array in **TWO** ways: using 'the Python way' and using a NumPy function

In [13]:
print(f"Using the Python way: {np.array([1, 2, 3])[::-1]}")
print(f"Using the NumPy function: {np.flip(np.array([1, 2, 3]))}")

Using the Python way: [3 2 1]
Using the NumPy function: [3 2 1]


In [14]:
# Expected output

#### 8. Create a 5x5 array with 1 on the border and 0 inside

In [15]:
arr = np.ones((5, 5))
arr[1:-1, 1:-1] = 0
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
# Expected output

#### 9. Add a border filled with 0's on the two sides of an array.

> Hint: [np.pad](https://numpy.org/doc/stable/reference/generated/numpy.pad.html)

In [17]:
arr = np.array([1, 2, 3])
np.pad(arr, 1)


array([0, 1, 2, 3, 0])

In [18]:
# Expected output

#### 10. Create an array of all the even integers from 10 to 50

In [19]:
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [20]:
# Expected output

#### 11. Create a 3x3 matrix with values ranging from 0 to 8

In [21]:
np.arange(0, 9).reshape((3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [22]:
# Expected output

#### 12. Create a 3x3 identity matrix

In [23]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
# Expected output

#### 13. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

> Hint: [np.diag](https://numpy.org/doc/stable/reference/generated/numpy.diag.html)

In [25]:
np.diag(np.arange(1, 5), -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [26]:
# Expected output

#### 14. Use NumPy to generate a random number between 0 and 1

**Note**: Your result's value should be different from the one shown below.

In [27]:
np.random.rand(1)

array([0.24085489])

In [28]:
# Expected output

#### 15. Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

**Note**: Your result's values should be different from the ones shown below.

In [29]:
np.random.randn(25)

array([-0.07429029, -1.18038448,  1.43874376,  0.76762646,  0.01672046,
       -1.36119007,  0.51435291,  0.82430248, -0.45703133,  1.01816153,
       -0.33372605,  2.24093211,  0.4976131 , -1.56810119, -0.62226477,
        1.99508238,  0.12407195,  0.86680516,  1.48188656,  0.12607324,
        1.13487757,  0.47561441, -1.58436312,  0.15878401, -1.10948493])

In [30]:
# Expected output

#### 16. Create a 3x3x3 array with random values drawn from the uniform distribution

**Note**: Your result's values should be different from the ones shown below.


In [31]:
np.random.rand(27).reshape((3, 3, 3))

array([[[0.45963714, 0.49063964, 0.10098113],
        [0.22671133, 0.59253056, 0.66515082],
        [0.04919992, 0.57832148, 0.45080703]],

       [[0.01389723, 0.73341598, 0.53414485],
        [0.54013663, 0.34510024, 0.81253036],
        [0.07502268, 0.45564938, 0.6031794 ]],

       [[0.98068125, 0.68505026, 0.80443747],
        [0.07258155, 0.09274496, 0.98665301],
        [0.39466636, 0.05718122, 0.72731853]]])

In [32]:
# Expected output

#### 17. Create a 10x10 array with random values drawn from the uniform distribution and find the minimum and maximum values.

**Note**: Your result's values should be different from the ones shown below.

In [33]:
arr = np.random.rand(100).reshape((10, 10))
print(f"The array: {arr}")
print(f"Its min value: {np.min(arr)}")
print(f"Its max value: {np.max(arr)}")



The array: [[0.47893026 0.01549302 0.5505981  0.07895945 0.62577598 0.80306998
  0.84685176 0.80439952 0.18718758 0.06248537]
 [0.98167755 0.19414734 0.78225953 0.27184792 0.11673915 0.37102039
  0.54896802 0.40075358 0.97202135 0.90357221]
 [0.1600636  0.13082979 0.15836397 0.76670512 0.8149834  0.74084189
  0.17765551 0.78108683 0.93479303 0.49025595]
 [0.62617926 0.18623755 0.01604677 0.02207778 0.5533418  0.91006247
  0.53124843 0.59322109 0.64328136 0.11754522]
 [0.69401986 0.85732332 0.72582276 0.08182924 0.48062194 0.25783516
  0.08669256 0.48608962 0.17558372 0.92145052]
 [0.4669365  0.55672044 0.69983283 0.19134891 0.9417456  0.56706821
  0.9347826  0.08551202 0.5574946  0.77272177]
 [0.89122907 0.96990092 0.79889627 0.93225192 0.36543083 0.08502577
  0.90757347 0.39690381 0.34036302 0.95083991]
 [0.61245459 0.91877968 0.18350773 0.55621763 0.64499407 0.70148493
  0.43404865 0.81622158 0.62952936 0.03542007]
 [0.5672593  0.68304184 0.65431665 0.38610086 0.46840903 0.76827547
 

In [34]:
# Expected output

#### 18. Create a random array with values drawn from the uniform distribution of size 30 and find the mean value

In [35]:
arr = np.random.rand(30)
print(f"The array: {arr}")
print(f"Its mean value: {np.mean(arr)}")

The array: [0.98010883 0.89699725 0.71509822 0.74205981 0.44032221 0.85300977
 0.80487406 0.7957866  0.9024472  0.50121912 0.10353976 0.07962202
 0.14522635 0.48513805 0.81607755 0.22770799 0.45221358 0.25811558
 0.14675649 0.20884521 0.7405122  0.53944126 0.5002183  0.62321947
 0.01615156 0.80340293 0.19912813 0.01943257 0.91332072 0.77391105]
Its mean value: 0.522796794984463


In [36]:
# Expected output

#### 19. Create the following matrix:

In [37]:
np.arange(1, 101).reshape((10, 10)) / 100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [38]:
# Expected output

#### 20. Create an array of 20 linearly spaced points between 0 and 1:

In [39]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [40]:
# Expected output

## Numpy Indexing and Selection

Now you will be given a starting matrix (be sure to run the cell below!), and be asked to replicate the resulting matrix outputs.

In all of the solutions until the last task before the section `NumPy Operations` you should be using `mat`.

In [41]:
# RUN THIS CELL - THIS IS OUR STARTING MATRIX
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### 21. Write code that reproduces the output shown below.

In [42]:
mat[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [43]:
# Expected output

#### 22. Write code that reproduces the output shown below.

In [44]:
mat[3, 4]

20

In [45]:
# Expected output

#### 23. Write code that reproduces the output shown below.

In [46]:
mat[:3, 1:2]

array([[ 2],
       [ 7],
       [12]])

In [47]:
# Expected output

#### 24. Write code that reproduces the output shown below.

In [48]:
mat[4, :]

array([21, 22, 23, 24, 25])

In [49]:
# Expected output

#### 25. Write code that reproduces the output shown below.

In [50]:
mat[3:5, :]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [51]:
# Expected output

#### 26. Find the indices of the non-zero elements in the provided array.

In [52]:
arr = np.array([1,2,0,0,4,0])
np.where(arr != 0)[0]
# Your code here

array([0, 1, 4])

In [ ]:
# Expected output

array([0, 1, 4])

## NumPy Operations

#### 27. Get the sum of all the values in mat

In [133]:
np.sum(mat)

325

In [ ]:
# Expected output

325

#### 28. Get the standard deviation of the values in mat

In [134]:
np.std(mat)

7.211102550927978

In [ ]:
# Expected output

7.211102550927978

#### 29. Get the sum of all the columns in mat

In [141]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [ ]:
# Expected output

array([55, 60, 65, 70, 75])

#### 30. Create and multiply a 5x3 matrix by a 3x2 matrix (matrix product). The matrices can hold random values or you can create them manually.

**Note**: In this example output the matrices held random values, so your result's values should be different from the ones shown below.

In [150]:
mat1 = np.random.rand(15).reshape((5, 3))
mat2 = np.random.rand(6).reshape((3, 2))

np.matmul(mat1, mat2)

array([[0.61686258, 0.69570062],
       [0.8381232 , 1.01982831],
       [0.72519803, 1.23910951],
       [0.42179752, 0.59368917],
       [1.05965181, 1.18471538]])

In [ ]:
# Expected output

array([[0.92284566, 0.4834381 ],
       [1.36591969, 0.86692985],
       [0.92732258, 0.57791729],
       [1.20870496, 0.66362074],
       [1.48551291, 0.86352205]])

#### 31. Create a 1D array of random integers between 0 and 9. Negate all elements which are between 3 and 8.

In [199]:
arr = np.random.randint(low=0, high=10, size=10)
mask = (arr >= 3) & (arr <= 8)
arr[mask] *= -1

arr

array([ 0, -6, -3,  0, -6, -3, -7, -5, -7, -5])

In [ ]:
# Expected output

array([ 4,  2,  5, -7, -2,  0, -3, -6, -8,  4])

#### 32. Create a random array of size 10 and sort it

In [204]:
arr = np.random.randint(low=0, high=10, size=10)
arr.sort()

arr

array([0, 2, 4, 4, 4, 6, 6, 8, 8, 8])

In [ ]:
# Expected output

array([0.21557229, 0.29775351, 0.31513898, 0.48094387, 0.56395818,
       0.61094507, 0.65782361, 0.73666887, 0.74573749, 0.97557176])

#### 33. Create random vector of values drawn from the uniform distribution of size 10 and replace the maximum value by 0

In [54]:
arr = np.random.rand(10)

print(f"The array: {arr}")

arr[np.argmax(arr)] = 0
print(f"Result: {arr}")


The array: [0.12578969 0.72040279 0.6601304  0.48315468 0.54700616 0.19131666
 0.58380851 0.30863401 0.00300249 0.47284211]
Result: [0.12578969 0.         0.6601304  0.48315468 0.54700616 0.19131666
 0.58380851 0.30863401 0.00300249 0.47284211]


In [ ]:
# Expected output

The array: [0.79753115 0.51085823 0.86710259 0.25025854 0.39803838 0.65002613
 0.89686752 0.1562022  0.76741728 0.62775096]
Result: [0.79753115 0.51085823 0.86710259 0.25025854 0.39803838 0.65002613
 0.         0.1562022  0.76741728 0.62775096]


#### 34. What function can we use to ensure that we always get the same random numbers?

seed