# Hello, [Tensorflow](https://www.tensorflow.org/api_docs)!

**But what is a tensor?**
 - (for the ML engineer) A tensor is a multidimensional array that can be stored and run on a GPU.
 - (for the mathematician) A generalization of a scalar, vector and matrix:
  - a scalar is a 0D tensor
  - a vector is a 1D tensor
  - a matrix is a 2D tensor

# Imports

In [52]:
%reset -f

In [53]:
import tensorflow as tf

**ALWAYS** check the tensorflow version. It gets updated really, REALLY frequently!

In [54]:
tf.__version__

'2.16.1'

## Initialization of Tensors

### Scalar (0D tensor)

In [55]:
x = tf.constant(4)
x

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [56]:
x = tf.constant(4.)
x

<tf.Tensor: shape=(), dtype=float32, numpy=4.0>

In [57]:
x.numpy()

4.0

### Vector (1D tensor)

In [58]:
x = tf.constant(4, shape=(1))
x

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([4], dtype=int32)>

In [59]:
x = tf.constant(4, shape=(5))
x

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([4, 4, 4, 4, 4], dtype=int32)>

In [60]:
x = tf.constant(4, shape=(5), dtype=tf.float32)
x

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([4., 4., 4., 4., 4.], dtype=float32)>

### Matrix (2D tensor)

In [61]:
x = tf.constant(4, shape=(4, 4))
x

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]], dtype=int32)>

In [62]:
x = tf.constant([[1, 2, 3], [4, 5, 6]])
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [63]:
tf.ones((3, 3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [64]:
tf.zeros((3, 3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [65]:
tf.eye(3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

### Sampling from the standard normal distribution

In [66]:
tf.random.normal((3, 3), mean=0, stddev=1)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.4696508 ,  0.3716814 , -1.3332932 ],
       [ 0.91341066, -2.1723275 , -0.04510928],
       [ 0.7112826 ,  1.1933422 , -0.7914751 ]], dtype=float32)>

### Sampling from the uniform distribution

In [67]:
tf.random.uniform((3, 3), minval=0, maxval=1)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.35078132, 0.25395513, 0.6577575 ],
       [0.65878344, 0.5426028 , 0.16556609],
       [0.04917157, 0.5691068 , 0.98968506]], dtype=float32)>

### Other useful functions

In [68]:
tf.range(9)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>

In [69]:
tf.range(start=5, limit=10)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([5, 6, 7, 8, 9], dtype=int32)>

In [70]:
x = tf.range(start=1, limit=10, delta=4)
x

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 5, 9], dtype=int32)>

### Casting

In [71]:
x.dtype

tf.int32

In [72]:
# Note that x does not change!
# This returns a new tensor.
tf.cast(x, tf.float32)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 5., 9.], dtype=float32)>

## Mathematical Operations

In [73]:
x = tf.constant([1, 2, 3])
y = tf.constant([9, 8, 7])

### Basic

In [74]:
x + y

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 10, 10], dtype=int32)>

In [75]:
x - y

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-8, -6, -4], dtype=int32)>

In [76]:
x * y

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 9, 16, 21], dtype=int32)>

In [77]:
x / y

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.11111111, 0.25      , 0.42857143])>

In [78]:
x / 0

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([inf, inf, inf])>

In [79]:
tf.add(x, y)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 10, 10], dtype=int32)>

In [80]:
tf.subtract(x, y)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-8, -6, -4], dtype=int32)>

In [81]:
tf.multiply(x, y)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 9, 16, 21], dtype=int32)>

In [82]:
tf.divide(x, y)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.11111111, 0.25      , 0.42857143])>

In [83]:
x ** 5

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([  1,  32, 243], dtype=int32)>

### Dot product

In [84]:
# Here, the `axes` parameter specifies along which axis to
# multiply the elements
tf.tensordot(x, y, axes=1)

<tf.Tensor: shape=(), dtype=int32, numpy=46>

In [85]:
tf.reduce_sum(x * y)

<tf.Tensor: shape=(), dtype=int32, numpy=46>

### Matrix multiplication

In [86]:
x = tf.random.normal((2, 3))
y = tf.random.normal((3, 4))

In [87]:
x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.4181365, -1.8484864, -1.7352504],
       [-1.2541164, -1.6732324,  0.9022355]], dtype=float32)>

In [88]:
y

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.6308225 ,  1.7266558 ,  1.065253  , -0.85883737],
       [ 0.92221737,  2.6160681 , -0.6360123 ,  0.8827329 ],
       [ 0.6472698 ,  1.3023818 ,  1.0120127 ,  0.02574759]],
      dtype=float32)>

In [89]:
x @ y

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[-2.5641117 , -6.373747  , -0.13501406, -2.0355096 ],
       [-1.7502191 , -5.367663  ,  0.641319  , -0.37670496]],
      dtype=float32)>

In [90]:
tf.matmul(x, y)

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[-2.5641117 , -6.373747  , -0.13501406, -2.0355096 ],
       [-1.7502191 , -5.367663  ,  0.641319  , -0.37670496]],
      dtype=float32)>

## Indexing

In [91]:
x = tf.constant([0, 1, 1, 2, 3, 1, 2, 3])
x

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([0, 1, 1, 2, 3, 1, 2, 3], dtype=int32)>

In [92]:
x[:]

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([0, 1, 1, 2, 3, 1, 2, 3], dtype=int32)>

In [93]:
x[5:]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [94]:
x[1:3]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 1], dtype=int32)>

In [95]:
x[::2]

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 3, 2], dtype=int32)>

In [96]:
x[::-1]

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([3, 2, 1, 3, 2, 1, 1, 0], dtype=int32)>

In [97]:
indices = tf.constant([0, 3])
tf.gather(x, indices)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 2], dtype=int32)>

In [98]:
tf.gather(x, [0, 3])

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 2], dtype=int32)>

## Reshaping

In [99]:
x = tf.range(9)
x

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>

In [100]:
x = tf.reshape(x, (3, 3))
x

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int32)>

In [101]:
tf.reshape(x, -1)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>